development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  API_KEY: <%= ENV['API_KEY'] %>
  PRIV_KEY: <%= ENV['PRIV_KEY'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  API_KEY: <%= ENV['API_KEY'] %>
  PRIV_KEY: <%= ENV['PRIV_KEY'] %>
